--- #YAML:1.0
name: Math-BigInt-Constant
version: 1.06
version_from: lib/Math/BigInt/Constant.pm
license: perl
distribution_type: module
generated_by: Math-BigInt-Constant version 1.06
installdirs: site
requires:
  Math::BigFloat: 1.48
  Math::BigInt: 1.74
  Test::Simple: 0.47
