# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Math-BigInt-Constant
version:      1.05
version_from: lib/Math/BigInt/Constant.pm
installdirs:  site
requires:
    Math::BigFloat:                1.43
    Math::BigInt:                  1.69
    Test::Simple:                  0.47

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
